# --- Font ---
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 10

# --- Look ---
background_opacity 0.76
window_padding_width 0
hide_window_decorations no
dynamic_background_opacity yes

# --- Behavior ---
enable_audio_bell no
confirm_os_window_close 0
scrollback_lines 10000
copy_on_select yes

shell fish


































































# ===== rice colors =====
background #1e2720
foreground #e0e8dc
cursor #7fb08a
selection_background #7fb08a
selection_foreground #1e2720
url_color #8fc4a0
