"""Rofi settings."""
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk
import os, subprocess
from apply_mixin import ApplyBar, DeferredSection
from config_utils import rofi as R

ROFI_THEME = os.path.expanduser("~/.config/rofi/theme.rasi")
ROFI_CONF = os.path.expanduser("~/.config/rofi/config.rasi")


def st(t):
    l = Gtk.Label(); l.set_markup(f'<span size="large" weight="bold">{t}</span>')
    l.set_xalign(0); l.get_style_context().add_class("section-title"); return l


def slider(label, mn, mx, step, init, cb):
    b = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    l = Gtk.Label(label=label); l.set_width_chars(22); l.set_xalign(0)
    l.get_style_context().add_class("param-label"); b.pack_start(l, False, False, 0)
    s = Gtk.Scale.new_with_range(Gtk.Orientation.HORIZONTAL, mn, mx, step)
    s.set_value(init); s.set_draw_value(True); s.set_value_pos(Gtk.PositionType.RIGHT)
    s.set_hexpand(True); s.get_style_context().add_class("param-slider")
    s.connect("value-changed", lambda w: cb(w.get_value()))
    b.pack_start(s, True, True, 0)
    return b, s


def entry_row(label, current, cb):
    b = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    l = Gtk.Label(label=label); l.set_width_chars(22); l.set_xalign(0)
    l.get_style_context().add_class("param-label"); b.pack_start(l, False, False, 0)
    e = Gtk.Entry(); e.set_text(current or ""); e.set_hexpand(True)
    e.connect("changed", lambda w: cb(w.get_text()))
    b.pack_start(e, True, True, 0)
    return b


def build_page(parent):
    scroll = Gtk.ScrolledWindow(); scroll.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.AUTOMATIC)
    box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=14); box.set_border_width(20); scroll.add(box)

    def on_apply(pending):
        r = R()
        for k, v in pending.items():
            r.set(k, v)

    def on_reload():
        pass  # Rofi reloads theme on each launch

    section = DeferredSection(on_apply=on_apply, on_reload=on_reload)
    r = R()

    title = Gtk.Label()
    title.set_markup('<span size="x-large" weight="bold">Rofi Launcher</span>')
    title.set_xalign(0); box.pack_start(title, False, False, 0)
    info = Gtk.Label()
    info.set_markup('<span size="small" color="#9c9c9c">Changes apply on next Rofi launch.</span>')
    info.set_xalign(0); box.pack_start(info, False, False, 0)

    box.pack_start(st("Window"), False, False, 10)
    v = r.get("width") or "30%"
    box.pack_start(entry_row("Width", v, lambda v: section.set("width", v)), False, False, 0)

    box.pack_start(st("Colors (from current theme)"), False, False, 10)
    for k, lbl in [("bg", "Background"), ("fg", "Foreground"), ("accent", "Accent")]:
        v = r.get(k) or "#000000"
        box.pack_start(entry_row(lbl, v, lambda v, kk=k: section.set(kk, v)), False, False, 0)

    box.pack_start(st("Info"), False, False, 10)
    info2 = Gtk.Label()
    info2.set_markup(f'<span size="small" color="#9c9c9c">Theme file: <b>{ROFI_THEME}</b>\nColors are auto-generated by Trinity theme-switch.</span>')
    info2.set_xalign(0); info2.set_line_wrap(True)
    box.pack_start(info2, False, False, 0)

    box.pack_start(Gtk.Separator(), False, False, 10)
    ob = Gtk.Button(label="Open Rofi theme in editor")
    ob.get_style_context().add_class("action-btn")
    ob.connect("clicked", lambda _: subprocess.Popen(["micro", ROFI_THEME]))
    box.pack_start(ob, False, False, 0)

    ob2 = Gtk.Button(label="Open Rofi config")
    ob2.connect("clicked", lambda _: subprocess.Popen(["micro", ROFI_CONF]))
    box.pack_start(ob2, False, False, 0)

    tb = Gtk.Button(label="Test Rofi")
    tb.connect("clicked", lambda _: subprocess.Popen(["rofi", "-show", "drun"]))
    box.pack_start(tb, False, False, 0)

    bar = ApplyBar(on_apply=section.apply, on_reset=section.reset)
    section.attach_bar(bar)
    box.pack_start(Gtk.Separator(), False, False, 10)
    box.pack_start(bar, False, False, 0)

    return scroll
